name: CI Input Aspects
on:
  pull_request:
    paths: ["NOTE-act-rules-common-aspects.bs"]
  push:
    branches: [main]
    paths: ["NOTE-act-rules-common-aspects.bs"]
  workflow_dispatch:
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 1
      matrix:
        include:
          - source: NOTE-act-rules-common-aspects.bs
            destination: /NOTE-act-rules-aspects/overview.html
            echidna_token: ECHIDNA_TOKEN_INPUT_ASPECTS
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed
          SOURCE: ${{ matrix.source }}
          DESTINATION: ${{ matrix.destination }}
          GH_PAGES_BRANCH: gh-pages
          # W3C_ECHIDNA_TOKEN: ${{ secrets[matrix.echidna_token] }}
          # W3C_WG_DECISION_URL: "https://lists.w3.org/Archives/Public/xyz.html"